embedding_model_name: text-embedding-v4
persist_directory: Chromadb/knowledge_file
reflection_collection_name: agent_reflections
separators: ["\n\n", "\n","|" ,"。", "？", "！", "，", ".", "?", "!", "," , " ", ""]
